allow_all_imports: true
hass_is_global: true
apps:

  dinamicBackground: 
    wallpaper_folder: '/config/www/images/wallpapers'
    homekit_infused_folder: '/config/hki-base/'
    wallpaper_selector_config_file: '/config/hki-user/wallpaper_selector_configs'

  importDashBoard: 
    homekit_dashboard_view_file: '/config/hki-user/config/view_config'
    homekit_dashboard_list_file: '/config/hki-user/dashboard_importer_configs'
    storage_folder: '/config/.storage' 
    devive_counter_file: '/config/hki-user/device_counters'
    entities_to_import: 
      - switch
      - light
      - sensor
      - weather
      - camera 
      
    cards_to_import: 
      - button
      - entities
      - light
      - entity
      - sensor
      - weather-forecast
      - picture-entity
      - picture-glance

  manageDashboards:
    file_auth: '/config/.storage/auth'
    file_person: '/config/.storage/person'
    hki_main_config_file: '/config/packages/homekit_infused/hki_configuration'
    hki_infused_template: '/config/hki-base/homekit-infused'
    base_template: '/config/hki-base/base'
    header_base_template: '/config/hki-base/templates/header/header-base-template'
    user_sensors_file: '/config/hki-user/user_sensors' 
    view_config_template: '/config/hki-user/config/view_config'
    general_config_template: '/config/hki-user/config/general_config'
    device_counter_file: '/config/hki-user/device_counters'
    dashboard_users_file: '/config/hki-user/dashboard_user_import_configs'

  homekitRedirect: 

  broadlink-raceland: 
    broadlink_config_file: "/config/broadlink_config/"
    storage_file: "configured_broadlink.json"
    storage_folder: "/config/.storage" 
    input_select_yaml_file: "/config/input_select.yaml"
    input_bool_yaml_file: "/config/input_boolean.yaml"
    input_select_dashboard: "dashboard_to_add"
    input_select_division: "division_to_add"
    input_select_remote: "broadlink_remote"
    remote_template_folder: "/config/remote_templates"
    remote_counter_name: "counter.remote_number_counter"
    base_bool_name: "learning_mode_remote"

  cameras-raceland: 
    camera_yaml_file: "/config/cameras.yaml"
    scrip_yaml_file: "/config/scripts.yaml"
    cameras_to_be_recorded: '/config/cameras_to_be_recorded.json'
    recordings_folder: '/config/www/camera_videos/'
    registered_cameras: "input_select.registered_cameras"
    input_select_file: "input_select"
    number_of_presets: 10
  
  camera-ai-raceland: 
    deepstack_yaml: "/config/deepstack"
    teach_face_preview_folder: "/config/www/screenshots_for_preview/"
    registered_cameras: "input_select.registered_cameras"
    current_camera_entity_id: "input_text.registered_cameras_entity_id"