entities:
  - cards:
      - icon: mdi:access-point
        entity: input_boolean.learning_mode_remote_number
        tap_action:
          action: toggle
        show_icon: true
        show_name: false
        style: |
          ha-card {
            box-shadow:
              {% if is_state('input_boolean.learning_mode_remote_number', 'on') %}
                -1px -1px 5px #0000FF , 1px 1px 0px #0000FF;
              {% elif is_state('input_boolean.learning_mode_remote_number', 'off') %} 
                -2px -2px 5px #2c2c2c , 2px 2px 5px #191919;
              {% endif %}
          }
        styles:
          card:
            - margin-top: 10px
            - margin-left: 3px
            - width: 60px
            - height: 60px
            - border-radius: 10px
            - background-color: var(--primary-background-color)
          icon:
            - color: var(--primary-text-color)
        type: custom:button-card
      - icon: mdi:car-back 
        tap_action:
          action: call-service
          service: broadlink_raceland.send_request
          service_data:
            command_name: garage_number
            mac_adress: mac
        show_icon: true
        show_name: false
        style: |
          ha-card {
            box-shadow:
              {% if is_state('input_boolean.learning_mode_remote_number', 'on') %}
                -1px -1px 5px #FFA500 , 1px 1px 5px #FFA500;
              {% elif is_state('input_boolean.learning_mode_remote_number', 'off') %} 
                -2px -2px 5px #2c2c2c , 2px 2px 5px #191919;
              {% endif %}
          }
        styles:
          card:
            - width: 60px
            - height: 60px
            - margin: 10px 10px 10px 80px
            - border-radius: 10px
            - background-color: var(--primary-background-color)
            - box-shadow: ''
          icon:
            - color: var(--primary-text-color)
        type: custom:button-card
    type: custom:hui-horizontal-stack-card
  - cards:
      - icon: mdi:lightbulb-outline
        tap_action:
          action: call-service
          service: broadlink_raceland.send_request
          service_data:
            command_name: light_number
            mac_adress: mac
        show_icon: true
        show_name: false
        style: |
          ha-card {
            box-shadow:
              {% if is_state('input_boolean.learning_mode_remote_number', 'on') %}
               -1px -1px 5px #FFA500 , 1px 1px 5px #FFA500;
              {% elif is_state('input_boolean.learning_mode_remote_number', 'off') %} 
               -2px -2px 5px #2c2c2c , 2px 2px 5px #191919;
              {% endif %}
             border-radius: 30px;
             background-color: var(--primary-background-color)
          }
        styles:
          card:
            - margin-top: 10px
            - margin-left: 3px
            - width: 60px
            - height: 60px
            - border-radius: 10px
            - background-color: var(--primary-background-color)
          icon:
            - color: var(--primary-text-color)
        type: custom:button-card
      - icon: mdi:lock
        tap_action:
          action: call-service
          service: broadlink_raceland.send_request
          service_data:
            command_name: lock_number
            mac_adress: mac
        show_icon: true
        show_name: false
        style: |
          ha-card {
            box-shadow:
              {% if is_state('input_boolean.learning_mode_remote_number', 'on') %}
                -1px -1px 5px #FFA500 , 1px 1px 5px #FFA500;
              {% elif is_state('input_boolean.learning_mode_remote_number', 'off') %} 
                -2px -2px 5px #2c2c2c , 2px 2px 5px #191919;
              {% endif %}
             border-radius: 30px;
             background-color: var(--primary-background-color)
          }
        styles:
          card:
            - margin-top: 10px
            - margin-left: 8px
            - width: 60px
            - height: 60px
            - border-radius: 10px
            - background-color: var(--primary-background-color)
          icon:
            - color: var(--primary-text-color)
        type: custom:button-card
      - icon: mdi:lock-open
        tap_action:
          action: call-service
          service: broadlink_raceland.send_request
          service_data:
            command_name: unlock_number
            mac_adress: mac
        show_icon: true
        show_name: false
        style: |
          ha-card {
            box-shadow:
              {% if is_state('input_boolean.learning_mode_remote_number', 'on') %}
                -1px -1px 5px #FFA500 , 1px 1px 5px #FFA500;
              {% elif is_state('input_boolean.learning_mode_remote_number', 'off') %} 
                -2px -2px 5px #2c2c2c , 2px 2px 5px #191919;
              {% endif %}
          }
        styles:
          card:
            - margin-top: 10px
            - margin-left: 8px
            - width: 60px
            - height: 60px
            - border-radius: 10px
            - background-color: var(--primary-background-color)
          icon:
            - color: var(--primary-text-color)
        type: custom:button-card
    type: custom:hui-horizontal-stack-card
show_header_toggle: false
style: |
  ha-card {
    box-shadow:
      {% if is_state('input_boolean.learning_mode_remote_number', 'on') %}
        -1px -1px 5px #FFA500 , 1px 1px 5px #FFA500;
      {% elif is_state('input_boolean.learning_mode_remote_number', 'off') %} 
        -2px -2px 5px #2c2c2c , 2px 2px 5px #191919;
      {% endif %}
    background-color: var(--primary-background-color);
    width: 250px;
    border-radius: 10px;
    margin: 10px auto;
  }
type: entities
