# lovelace_gen

# Card
type: picture-elements
style: |
  ha-card {
    border-radius: var(--border-radius);
    box-shadow: var(--box-shadow);
    overflow: hidden;
  }
image: "{{ image }}"
elements:
  - type: state-label
    entity: "{{ entity_status }}"
    style:
      left: 0
      bottom: 0
      pointer-events: none
      font-size: 13px
      font-family: var(--font-family)
      line-height: 15px
      text-align: end
      color: white
      background-color: rgba(0, 0, 0, 0.3)
      width: 100%
      transform: initial
      text-transform: capitalize
  - type: state-label
    entity: "{{ sensor_plate }}"
    style:
      top: 0
      right: 0
      pointer-events: none
      transform: initial
      font-size: 12px
      font-weight: bold
      font-family: var(--font-family)
      color: black
      line-height: 32px
      padding: 2px 35px
  - type: icon
    icon: {{ icon_plate }}
    style:
      top: 0
      right: 0
      pointer-events: none
      transform: scale(0.8)
      color: black
      line-height: 32px
      padding: 8px 13px
  - type: state-label
    entity: "{{ sensor_insured }}"
    style:
      top: 0
      right: 0
      pointer-events: none
      transform: initial
      font-size: 12px
      font-weight: bold
      font-family: var(--font-family)
      color: black
      line-height: 32px
      padding: 28px 35px
  - type: icon
    icon: {{ icon_insured }}
    style:
      top: 0
      right: 0
      pointer-events: none
      transform: scale(0.8)
      color: black
      line-height: 32px
      padding: 35px 13px

                
          