# lovelace_gen

type: picture-elements
style: |
  ha-card {  
    border-radius: var(--border-radius);
    box-shadow: var(--box-shadow);
    overflow: hidden;
  }
image: {{ image_path }}
elements:
  - type: image
    entity: {{ person }}
    image: {{ image_path }}
    tap_action:
      action: navigate
      navigation_path: /homekit-infused/{{ navigation_path }}
    hold_action:
      action: none
    style:
      left: 50%
      top: 50%
      width: 100%
      heigth: 100%
  - type: state-label
    entity: {{ person }}
    style:
      left: 0
      bottom: 0
      pointer-events: none
      font-size: 13px
      font-family: var(--font-family)
      line-height: 15px
      color: {{ text_color }}
      background-color: rgba(0, 0, 0, 0.3)
      width: 100%
      transform: initial
      text-align: {{alignment}}