Preto:

  ### Theme Raceland Theme Dark (modified) for Raceland Homeassistant Dashboard

  ## User Settings

  ### Background image (can be an image or a color)
  background-image: '#222222'
  primary-background-color: 'var(--background-image)'
  background-video: "/local/videdim/9m11gd43m6qn3y93ntzp.hd.mp4"
  ### Header Title and Subtitle/Notifications
  header-text-color: 'White'
  header-font-size: 15px
  header-font-weight: normal
  header-shadow: 0px 14px 21px -15px rgba(0,0,0,0.75)

  subtitle-text-color: 'White'
  subtitle-font-size: 12px
  subtitle-font-weight: normal

  ### Title Text Addon
  title-text-color: 'White'
  title-text-font-size: 15px
  title-text-font-weight: bolder

  ### Display a gap at the left and right side of cards on a smartphone
  display-gap: 10px

  ### Border Radius and Box Shadow
  border-radius: 15px
  box-shadow: var(--ha-card-box-shadow, 2px 6px 2px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12) )
  bar-card-border-radius: 12px

  ### Button Colors
  button-color: '#262628'

  button-on-color: '#FFFFFF'
  button-on-name-color: black
  button-on-state-color: black
  button-on-label-color: gray
  button-on-lock-color: gray
  button-on-icon-color: var(--paper-item-icon-active-color)
  button-on-opacity: 1
  button-on-box-shadow: none


  ### Fonts
  font-family: Roboto

  name-font-size: 10px
  name-font-weight: bold

  label-font-size: 10px
  label-font-weight: normal

  state-font-size: 8px
  state-font-weight: bold

  ### Badges
  badge-font-size: 10px
  badge-font-weight: normal
  badge-text-transform: capitalize
  label-badge-background-color: "#262628"

  #######################################################################################################################################################
  ## Main Home Assistant Colors (ANYTHING YOU CHANGE PAST THIS LINE, IS AT YOUR OWN RISK!)

  # Card Mod
  card-mod-theme: Raceland Theme Dark (HKI Edition)
  card-mod-root-yaml: |
    .: |
      {% if is_state('input_select.navigation_bar', 'Bottom') %}
      ha-menu-button {
        display: none !important;
      }
      @media (orientation: portrait) {
        paper-icon-button[icon="paper-tabs:chevron-right"] {
          display: none;
        }
        paper-icon-button[icon="paper-tabs:chevron-left"] {
          display: none;
        }
      }
      mwc-icon-button[slot="trigger"] > ha-svg-icon {
        display: none;
      }
      mwc-icon-button[slot="trigger"]::after {
        font-size: 18px;
        height: 20px;
        width: 150px;

        {% if is_state('input_select.navigation_bar_direction', 'Right') %}
        text-align: left;
        position: absolute;
        top: 14px;
        right: 12px;
        transform: rotateY(180deg) !important;
        color: var(--header-text-color) !important;

        {% else %}
        text-align: right;
        position: absolute;
        top: 14px;
        right: 12px;
        transform: none
        color: var(--header-text-color) !important;

        {% endif %}

        color: var(--header-text-color) !important;

        {% if is_state('input_select.navigation_bar_options', 'User') %}
        content: "{{ user }}";

        {% elif is_state('input_select.navigation_bar_options', 'Date') %}
        content: "{{ states('sensor.date') }}";

        {% elif is_state('input_select.navigation_bar_options', 'Time') %}
        content: "{{ states('sensor.time') }}";

        {% else %}
        display: none !important;

        {% endif %}

      }
      app-header {
        top: auto !important;
        bottom: 0 !important;
        transform: unset !important;
        box-shadow: 0px -10px 21px -15px rgba(0,0,0,0.75);
      }
      app-toolbar {
        {% if is_state('input_select.navigation_bar_direction', 'Right') %}
        transform: rotateY(180deg) !important;
        {% else %}
        transform: none
        {% endif %}
      }
      ha-tabs {
        --paper-tabs-selection-bar-color: var(--primary-color) !important;
      }
      [main-title] {
        color: var(--primary-color) !important;
      }
      paper-tab {
        {% if is_state('input_select.navigation_bar_direction', 'Right') %}
        transform: rotateY(180deg) !important;
        {% else %}
        transform: none;
        {% endif %}
      }
      #view {
        margin-top: -56px !important;
      }
      ha-icon {

        color: var(--header-text-color) !important;
      }

      {% elif is_state('input_select.navigation_bar', 'Top') %}
      ha-menu-button {
        display: none !important;
      }
      @media (orientation: portrait) {
        paper-icon-button[icon="paper-tabs:chevron-right"] {
          display: none;
        }
        paper-icon-button[icon="paper-tabs:chevron-left"] {
          display: none;
        }
      }
      mwc-icon-button[slot="trigger"] > ha-svg-icon {
        display: none;
      }
      mwc-icon-button[slot="trigger"]::after {
        font-size: 18px;
        height: 20px;
        width: 150px;

        {% if is_state('input_select.navigation_bar_direction', 'Right') %}
        text-align: left;
        position: absolute;
        top: 14px;
        right: 12px;
        transform: rotateY(180deg) !important;
        color: var(--header-text-color) !important;

        {% else %}
        text-align: right;
        position: absolute;
        top: 14px;
        right: 12px;
        transform: none
        color: var(--header-text-color) !important;

        {% endif %}

        color: var(--header-text-color) !important;

        {% if is_state('input_select.navigation_bar_options', 'User') %}
        content: "{{ user }}";

        {% elif is_state('input_select.navigation_bar_options', 'Date') %}
        content: "{{ states('sensor.date') }}";

        {% elif is_state('input_select.navigation_bar_options', 'Time') %}
        content: "{{ states('sensor.time') }}";

        {% else %}
        display: none !important;

        {% endif %}

      }
      app-header {
        box-shadow: none !important;
      }
      app-toolbar {
        {% if is_state('input_select.navigation_bar_direction', 'Right') %}
        transform: rotateY(180deg) !important;
        {% else %}
        transform: none
        {% endif %}
      }
      ha-tabs {
        --paper-tabs-selection-bar-color: var(--primary-color) !important;
      }
      [main-title] {
        color: var(--primary-color) !important;
      }
      paper-tab {
        {% if is_state('input_select.navigation_bar_direction', 'Right') %}
        transform: rotateY(180deg) !important;
        {% else %}
        transform: none;
        {% endif %}
      }
      ha-icon {

        color: var(--header-text-color) !important;
      }
      {% endif %}

  # Toast / Badge
  paper-toast-background-color: '#821414'

  #color for top small bar notch on ios
  primary-color: '#262628'
  primary-text-color: '#f2f2f7'
  text-primary-color: 'var(--primary-text-color)'
  secondary-text-color: 'var(--primary-text-color)'

  #left header

  #left sidebar
  paper-listbox-background-color: '#121314' #background
  sidebar-icon-color: '#d0d0d0'
  sidebar-selected-icon-color: '#2fbae5'
  sidebar-selected-text-color: '#ffffff'

  #Paper cards
  paper-card-header-color: 'var(--primary-text-color)'
  ha-card-background: 'var(--button-color)'
  paper-card-background-color: 'var(--ha-card-background)' # 'rgba(52, 73, 94, 0.8)'
  paper-dialog-background-color: '#262628'
  paper-item-icon-color: 'var(--primary-text-color)'
  paper-item-icon-active-color: '#b58e31'
  paper-item-icon_-_color: 'var(--primary-text-color)'
  paper-item-selected_-_background-color: '#262628'
  paper-tabs-selection-bar-color: 'var(--primary-text-color)'
  secondary-background-color: '#262628'

  mdc-theme-primary: '#fafafa'

  #Tables
  card-background-color: '#262628'
  table-row-background-color: '#6e6e6e'
  table-row-alternative-background-color: 'darkgrey'

  #Custom header
  ch-active-tab-color: '#2fbae5'
  ch-tab-indicator-color: '#2fbae5'

  # Labels
  label-badge-red: 'var(--primary-color)'
  label-badge-text-color: 'var(--primary-text-color)'
  # label-badge-background-color: 'var(--mdc-grey-darken-4)'

  # Switches
  paper-toggle-button-checked-button-color: 'var(--light-primary-color)'
  paper-toggle-button-checked-bar-color: 'var(--light-primary-color)'
  paper-toggle-button-checked-ink-color: 'var(--light-primary-color)'
  paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
  switch-checked-color: 'var(--paper-slider-knob-color)'

  # Sliders
  paper-slider-knob-color: '#2fbae5'
  paper-slider-knob-start-color: 'var(--light-primary-color)'
  paper-slider-pin-color: 'var(--light-primary-color)'
  paper-slider-active-color: '#2fbae5'
  paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
  paper-slider-secondary-color: 'var(--secondary-background-color)'
  paper-slider-disabled-active-color: 'var(--disabled-text-color)'
  paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'

  # Google colors
  google-red-500: '#de0000'
  google-green-500: 'gray'

  # History/Logbook
  lumo-primary-text-color: 'white'
  lumo-secondary-text-color: 'white'
  lumo-primary-color: 'white'
  lumo-body-text-color: 'AliceBlue' # Calendar Day
  lumo-base-color: 'white' #Calendar/Date-Picker Background
  lumo-header-text-color: 'white' #Month/Year header

  #DayOfWeek Header
  lumo-tertiary-text-color: 'white'
  lumo-shade: 'grey'
  lumo-shade-90pct: 'rgba(34, 34, 34, .9)'
  lumo-shade-80pct: 'rgba(34, 34, 34, .8)'
  lumo-shade-70pct: 'rgba(34, 34, 34, .7)'
  lumo-shade-60pct: 'rgba(34, 34, 34, .6)'
  lumo-shade-50pct: 'rgba(34, 34, 34, .5)'
  lumo-shade-40pct: 'rgba(34, 34, 34, .4)'
  lumo-shade-30pct: 'rgba(34, 34, 34, .3)'
  lumo-shade-20pct: 'rgba(34, 34, 34, .2)'
  lumo-shade-10pct: 'rgba(34, 34, 34, .1)'
  lumo-shade-5pct: 'rgba(34, 34, 34, .05)'
  lumo-tint-5pct: 'grey'