# lovelace_gen

# card
type: custom:button-card
template: 
  - style-default
  - {{ grid|default('default-hki-grid') }}
name: "{{ name }}"
icon: "{{ icon }}"
show_entity_picture: {{ show_entity_picture|default('true') }}
entity_picture: "{{ entity_picture }}"
color: {{ color|default('auto') }}
size: {{ size|default('25%') }}
lock:
  enabled: {{ lock|default('false') }}
  unlock: {{ lock_unlock|default('tap') }}
  duration: {{ lock_duration|default('5') }}
aspect_ratio: {{ aspect_ratio|default('1/1') }}
entity: {{ entity }}
label: "{{ label|default('&nbsp;') }}"
show_name: {{ show_name|default('true') }}
show_icon: {{ show_icon|default('true') }}
show_state: {{ show_state|default('true') }}
show_label: {{ show_label|default('true') }}
show_last_changed: {{ show_last_changed|default('false') }}
tap_action: 
state:
  - value: "on" 
    spin: {{ spin_on|default('false') }} 
    styles:
      card:
        - --ha-card-background: {{ ha_card_background|default('var(--button-on-color)') }}
        - opacity: var(--button-on-opacity)
        - -webkit-box-shadow: var(--button-on-box-shadow)
        - box-shadow: var(--button-on-box-shadow)
      name:
        - color: var(--button-on-name-color)
      state:
        - color: var(--button-on-state-color)
      lock:
        - color: var(--button-on-lock-color) 
      label:
        - color: var(--button-on-label-color)
  - value: "off"
    spin: {{ spin_off|default('false') }}
    styles:
      card:
        - opacity: {{ opacity_off|default('0.5') }}
      icon:
        - color: {{ icon_color_off|default('var(--paper-item-icon-color)') }}
      name:
        - color: var(--primary-text-color)
      state:
        - color: var(--primary-text-color)
      label:
        - color: var(--primary-text-color)
      lock:
        - color: var(--primary-text-color)
  - value: "unavailable"
    styles:
      card:
        - opacity: 0.2
      icon:
        - color: {{ icon_color_off|default('var(--paper-item-icon-color)') }}
      name:
        - color: var(--primary-text-color)
      state:
        - color: hsl(0, 100%, 50%)
      label:
        - color: var(--primary-text-color)
      lock:
        - color: var(--paper-item-icon-color)
  - value: "scening"
    spin: {{ spin_off|default('false') }}
    styles:
      card:
        - opacity: {{ opacity_off|default('0.8') }}
      icon:
        - color: {{ icon_color_off|default('var(--paper-item-icon-color)') }}
      name:
        - color: var(--primary-text-color)
      state:
        - color: var(--primary-text-color)
      label:
        - color: var(--primary-text-color)
      lock:
        - color: var(--paper-item-icon-color)
  - value: 1000
    operator: '<='
    color: {{ icon_color_off|default('var(--paper-item-icon-color)') }}