# lovelace_gen

# card
type: custom:button-card
name: "{{ name }}"
icon: "{{ icon }}"
size: 25%
aspect_ratio: "{{ aspect_ratio|default('1/1') }}"
label: "{{ label|default('&nbsp;') }}"
show_name: {{ show_name|default('true') }}
show_icon: {{ show_icon|default('true') }}
show_state: {{ show_state|default('false') }}
show_label: {{ show_label|default('true') }}
entity: {{ entity }}
tap_action: 
  action: call-service
  service: {{ service|default('input_select.select_option') }}
  service_data:
    entity_id: {{ service_entity }}
    "{{extra|default('option') }}": "{{ option }}"
  haptic: heavy
hold_action:
  action: {{ hold_action|default('none') }}
double_tap_action:
  action: more-info
styles:
  card:
    - border-radius: var(--border-radius)
    - box-shadow: var(--box-shadow)
    - opacity: 1.0
  name:
    - font-weight: var(--name-font-weight)
    - font-family: var(--font-family) 
    - font-size: 10px