# lovelace_gen

# card
type: custom:button-card
name: "{{ name }}"
icon: "{{ icon }}"
size: 25%
aspect_ratio: {{ aspect_ratio|default('1/1') }}
entity: {{ entity }}
label: "{{ label|default('&nbsp;') }}"
show_name: {{ show_name|default('true') }}
show_icon: {{ show_icon|default('true') }}
show_state: {{ show_state|default('false') }}
show_label: {{ show_label|default('true') }}
tap_action: 
  action: call-service
  service: {{ service|default('scene.turn_on') }}
  service_data:
    entity_id: "{{ service_entity }}"
  haptic: heavy
hold_action:
  action: none
styles:
  card:
    - border-radius: var(--border-radius)
    - box-shadow: var(--box-shadow)
    - opacity: 1.0
  name:
    - font-weight: var(--name-font-weight)
    - font-family: var(--font-family) 
    - font-size: 10px

state:
  - value: "on" 
    spin: {{ spin_on|default('false') }} 
    styles:
      card:
        - --ha-card-background: {{ ha_card_background|default('var(--button-on-color)') }}
        - opacity: var(--button-on-opacity)
        - -webkit-box-shadow: var(--button-on-box-shadow)
        - box-shadow: var(--button-on-box-shadow)
      name:
        - color: var(--button-on-name-color)
      state:
        - color: var(--button-on-state-color)
      lock:
        - color: var(--button-on-lock-color) 
      label:
        - color: var(--button-on-label-color)
  - value: "unknown" 
    spin: {{ spin_on|default('false') }} 
    styles:
      card:
        - --ha-card-background: white
        - opacity: 1.0
        - box-shadow: none
      name:
        - color: black 
      state:
        - color: black 
      lock:
        - color: gray
      label:
        - color: gray
  - value: "off"
    spin: {{ spin_off|default('false') }}
    styles:
      card:
        - opacity: {{ opacity_off|default('0.8') }}
        - --ha-card-background: "{{ card_color_off|default('var(--ha-card-background)') }}"
      icon:
        - color: "{{ icon_color_off|default('var(--paper-item-icon-color)') }}"
        - animation: {{ animation|default('none') }}
      name:
        - color: "{{ name_color_off|default('var(--primary-text-color)') }}"
      state:
        - color: "{{ state_color_off|default('var(--primary-text-color)') }}"
      label:
        - color: "{{ label_color_off|default('var(--primary-text-color)') }}"
