# lovelace_gen

# card
type: custom:light-popup-card
entity: {{ entity }}
brightnessWidth: 110px
brightnessHeight: {{ slider_height|default('410px') }}
displayType: {{ display_type|default('auto') }}
fullscreen: false
settings: true
settingsPosition: bottom
settingsCard:
  type: custom:more-info-card
  cardOptions:
    entity: {{ entity }}
actionsInARow: 3
actionSize: 30px
actions:
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      brightness: 85
    color: '#DCDCDC'
    
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      brightness: 190
    color: '#F0F0F0'
  - service: light.turn_on
    service_data:
      entity_id: {{ entity }}
      brightness: 255
    color: '#FFFFFF'
