
##########################
###  Theme Automation  ###
##########################

##Theme selector
- alias: 'themes'
  trigger:
    - platform: state
      entity_id: input_select.theme_selector
  action:
    - service: frontend.set_theme
      data_template:
        name: >
          {{ states('input_select.theme_selector') }}


#Note: The following code can be adapted if we want to settup a night and day theme for homekit (the theme will change when the sun sets). When this is implemented replaces the above automation

# - alias: 'themes'
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: input_boolean.day_night_cycle
#     - platform: state
#       entity_id: input_select.theme_selector
#     - platform: state
#       entity_id: input_select.theme_selector_day
#     - platform: state
#       entity_id: input_select.theme_selector_night
#     - platform: state
#       entity_id: sun.sun
#   action:
#     - service: frontend.set_theme
#       data_template:
#         name: >
#           {% if (is_state('sun.sun', 'above_horizon')) and (is_state('input_boolean.day_night_cycle', 'on'))  %}
#             {{ states('input_select.theme_selector_day') }}
#           {% elif (is_state('sun.sun', 'below_horizon')) and (is_state('input_boolean.day_night_cycle', 'on'))  %}
#             {{ states('input_select.theme_selector_night') }}
#           {% else %}
#             {{ states('input_select.theme_selector') }}
#           {% endif %}
