name: Wallpaper selector
options:
- Theme wallpaper
- blue-wood.png
- gray-wood.png
- home-assistant.png
- ios13-homekit-dark-blue.png
- ios13-homekit-dark-green.png
- ios13-homekit-light-green.png
- ios13-homekit-orange.png
- ios13-homekit-red.png
- love-red.jpg
- pink-flowers.jpg
- popup-wallpaper-gray.png
- popup-wallpaper-pink.png
- popup-wallpaper-red.png
- valentine-test.jpg
- valentines-day-2.jpg
- valentines-day.jpg
- white-gradient.png
