state:
  - value: "off"
    styles:
      card:
        - opacity: 1.0
      icon:
        - color: var(--paper-item-icon-color)
      name:
        - color: var(--primary-text-color)
      state:
        - color: var(--primary-text-color)
      label:
        - color: var(--primary-text-color)
      lock:
        - color: var(--primary-text-color)