# This is the grid used for light and device buttons.
# This will make the state and label appear horizontally
# at the bottom of the button. More grids might be added
# in the future.

#### #### #### #### #### #### #### #### #### #### #### #

# Card Config
# Do NOT change this unless you know what you are doing!
- grid-template-areas: |
            "icon  circle"
            "n     n"
            "s     s"
- grid-template-columns: repeat(2, 1fr)
- grid-template-rows: auto repeat(2, min-content)
- gap: 2%
- align-items: start